### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by TiborUdvari** [dopey/aenea-fork#1]
Hello, 

Could you give a workflow of how to test/launch the service? 

I'm a little confused of what goes where and what is executed when. 

It also appears there are some hardcoded paths in the project that may not be ok. 
Is there a how to use part of this project somewhere? 

```
aenea-fork-master/util/proxy_actions.py:
   42        return [line.strip() for line in keyfile] + list(WINDOWS_MAPPING)
   43    except Exception:
   44:     with open("Z:\\SHARED\\aenea\\util\\keys.txt") as keyfile:
   45        return [line.strip() for line in keyfile] + list(WINDOWS_MAPPING)
   46  

aenea-fork-master/util/reload_grammar.py:
    3  
    4  def reload_grammar():
    5:   for name in os.listdir("Z:\\SHARED\\aenea\\grammar"):
    6      if name.endswith(".py"):
    7:       with open("Z:\\SHARED\\aenea\\grammar\\%s" % name) as infd:
    8          with open("C:\\NatLink\\NatLink\\MacroSystem\\_%s" % name, "w") as outfd:
    9            outfd.write(infd.read())
```

**Comment by dopey** [comment]
Hey @TiborUdvari, unfortunately its been nearly 3 years since I was actively working on this, and ~2years since I still had the laptop that had the VM, the SHARED folder, and the settings in place. I think that I'm too far removed to be able to remember (or even access) anything useful. Sorry :(

**Comment by TiborUdvari** [comment]
Ok thanks. I was still hoping that maybe you were using your system. I'll try to take a deeper look maybe I can fix it myself. Cheers.
